package cmd

import (
	"fmt"
	"os/exec"
	"strings"

	"github.com/spf13/cobra"

	"github.com/crvgilbertson/intentra/cmd/ui"
	"github.com/crvgilbertson/intentra/engine/models"
)

var (
	prTitle string
	prBase  string
	prDraft bool
)

var prCmd = &cobra.Command{
	Use:   "pr",
	Short: "Create a GitHub pull request from the current branch",
	Long:  "Pushes the current branch and opens a GitHub PR. Title and body are derived from the cached commit plan if available, or from git log as a fallback. Requires the gh CLI.",
	RunE:  runPR,
}

func init() {
	prCmd.Flags().StringVar(&prTitle, "title", "", "PR title (auto-generated if omitted)")
	prCmd.Flags().StringVar(&prBase, "base", "", "base branch (default: first protected branch from config, or main)")
	prCmd.Flags().BoolVar(&prDraft, "draft", false, "create as draft PR")
	rootCmd.AddCommand(prCmd)
}

func runPR(cmd *cobra.Command, args []string) error {
	if err := requireGH(); err != nil {
		return err
	}

	branch, err := currentBranch()
	if err != nil {
		return fmt.Errorf("could not determine current branch: %w", err)
	}

	base := prBase
	if base == "" {
		if len(cfg.Engine.ProtectedBranches) > 0 {
			base = cfg.Engine.ProtectedBranches[0]
		} else {
			base = "main"
		}
	}

	if strings.EqualFold(branch, base) {
		return fmt.Errorf("currently on %q which is the base branch — create a feature branch first", branch)
	}

	remote := cfg.Engine.RemoteName
	if remote == "" {
		remote = "origin"
	}

	ui.Info("Pushing %s to %s...\n", branch, remote)
	if !smartPush(remote, branch) {
		return fmt.Errorf("push failed — cannot create PR without pushing")
	}

	title, body := buildPRContent()

	if prTitle != "" {
		title = prTitle
	}

	ghArgs := []string{"pr", "create", "--title", title, "--body", body, "--base", base}
	if prDraft {
		ghArgs = append(ghArgs, "--draft")
	}

	ui.Info("Creating PR: %s -> %s\n", branch, base)

	out, err := exec.Command("gh", ghArgs...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("gh pr create failed: %s", strings.TrimSpace(string(out)))
	}

	url := strings.TrimSpace(string(out))
	ui.Success("\nPR created: %s\n", url)
	return nil
}

func buildPRContent() (title, body string) {
	cached, err := loadCachedPlan()
	if err == nil && len(cached.Commits) > 0 {
		return buildPRFromPlan(cached)
	}
	return buildPRFromGitLog()
}

func buildPRFromPlan(cp *models.CommitPlan) (title, body string) {
	if len(cp.Commits) == 1 {
		title = cp.Commits[0].FullSubject()
	} else {
		types := summarizeCommitTypes(cp.Commits)
		title = fmt.Sprintf("%d changes: %s", len(cp.Commits), types)
	}

	var sb strings.Builder
	sb.WriteString("## Changes\n\n")
	for i, c := range cp.Commits {
		sb.WriteString(fmt.Sprintf("%d. **%s**: %s\n", i+1, c.FullSubject(), commitFileList(c)))
		if c.Body != nil && *c.Body != "" {
			sb.WriteString(fmt.Sprintf("   %s\n", *c.Body))
		}
	}
	sb.WriteString(fmt.Sprintf("\n---\n*Generated by intentra %s*\n", cp.ToolVersion))
	body = sb.String()
	return
}

func summarizeCommitTypes(commits []models.CommitUnit) string {
	seen := make(map[string]bool)
	var types []string
	for _, c := range commits {
		label := c.Type
		if c.Scope != nil && *c.Scope != "" {
			label += "(" + *c.Scope + ")"
		}
		if !seen[label] {
			seen[label] = true
			types = append(types, label)
		}
	}
	if len(types) > 5 {
		return strings.Join(types[:5], ", ") + fmt.Sprintf(" +%d more", len(types)-5)
	}
	return strings.Join(types, ", ")
}

func commitFileList(c models.CommitUnit) string {
	if len(c.Hunks) == 0 {
		return ""
	}
	return fmt.Sprintf("(%d hunk(s))", len(c.Hunks))
}

func buildPRFromGitLog() (title, body string) {
	out, err := exec.Command("git", "log", "--oneline", "-20", "--no-decorate").Output()
	if err != nil || len(strings.TrimSpace(string(out))) == 0 {
		return "Pull request", "Created with intentra."
	}

	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	if len(lines) == 1 {
		parts := strings.SplitN(lines[0], " ", 2)
		if len(parts) == 2 {
			title = parts[1]
		} else {
			title = lines[0]
		}
	} else {
		title = fmt.Sprintf("%d commits", len(lines))
	}

	var sb strings.Builder
	sb.WriteString("## Commits\n\n")
	for _, line := range lines {
		sb.WriteString(fmt.Sprintf("- %s\n", line))
	}
	body = sb.String()
	return
}
