package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/spf13/cobra"

	"github.com/crvgilbertson/intentra/cmd/ui"
	"github.com/crvgilbertson/intentra/engine/artifacts"
	"github.com/crvgilbertson/intentra/engine/models"
)

var (
	prTitle  string
	prBase   string
	prDraft  bool
	prTicket string
)

var prCmd = &cobra.Command{
	Use:   "pr",
	Short: "Create a GitHub pull request from the current branch",
	Long:  "Pushes the current branch and opens a GitHub PR. Title and body are derived from the cached commit plan if available, or from git log as a fallback. Requires the gh CLI.",
	RunE:  runPR,
}

func init() {
	prCmd.Flags().StringVar(&prTitle, "title", "", "PR title (auto-generated if omitted)")
	prCmd.Flags().StringVar(&prBase, "base", "", "base branch (default: first protected branch from config, or main)")
	prCmd.Flags().BoolVar(&prDraft, "draft", false, "create as draft PR")
	prCmd.Flags().StringVar(&prTicket, "ticket", "", "ticket reference to include (for example PROJ-123)")
	rootCmd.AddCommand(prCmd)
}

func runPR(cmd *cobra.Command, args []string) error {
	if err := requireGH(); err != nil {
		return err
	}

	branch, err := currentBranch()
	if err != nil {
		return fmt.Errorf("could not determine current branch: %w", err)
	}

	base := prBase
	if base == "" {
		if len(cfg.Engine.ProtectedBranches) > 0 {
			base = cfg.Engine.ProtectedBranches[0]
		} else {
			base = "main"
		}
	}

	if strings.EqualFold(branch, base) {
		return fmt.Errorf("currently on %q which is the base branch — create a feature branch first", branch)
	}

	remote := cfg.Engine.RemoteName
	if remote == "" {
		remote = "origin"
	}

	if !smartPush(remote, branch) {
		return fmt.Errorf("push failed — cannot create PR without pushing")
	}

	title, body := buildPRContent(base, prTicket)

	if prTitle != "" {
		title = prTitle
	}

	bodyFile, err := os.CreateTemp("", "intentra-pr-body-*.md")
	if err != nil {
		return fmt.Errorf("creating temp body file: %w", err)
	}
	defer os.Remove(bodyFile.Name())

	if _, err := bodyFile.WriteString(body); err != nil {
		bodyFile.Close()
		return fmt.Errorf("writing PR body: %w", err)
	}
	bodyFile.Close()

	ghArgs := []string{"pr", "create", "--title", title, "--body-file", bodyFile.Name(), "--base", base}
	if prDraft {
		ghArgs = append(ghArgs, "--draft")
	}

	ui.Info("Creating PR: %s -> %s\n", branch, base)

	ghCtx, ghCancel := netCtx()
	defer ghCancel()
	out, err := exec.CommandContext(ghCtx, "gh", ghArgs...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("gh pr create failed: %s", strings.TrimSpace(string(out)))
	}

	url := strings.TrimSpace(string(out))
	ui.Success("\nPR created: %s\n", url)
	return nil
}

func buildPRContent(base, explicitTicket string) (title, body string) {
	cached, err := loadCachedPlan()
	if err == nil && len(cached.Commits) > 0 && planMatchesHead(cached) {
		return buildPRFromPlan(cached, resolveTicketRef(explicitTicket, cached))
	}
	return buildPRFromGitLog(base, resolveTicketRef(explicitTicket, nil))
}

// planMatchesHead returns true if the cached plan's base ref is an ancestor
// of the current HEAD, meaning the plan's commits are still part of HEAD's
// history and the plan is valid for PR content.
func planMatchesHead(cp *models.CommitPlan) bool {
	if cp.BaseRef == "" || cp.BaseRef == "WORKING_TREE" {
		return false
	}
	ctx, cancel := localCtx()
	defer cancel()
	return exec.CommandContext(ctx, "git", "merge-base", "--is-ancestor", cp.BaseRef, "HEAD").Run() == nil
}

func buildPRFromPlan(cp *models.CommitPlan, ticket *artifacts.TicketRef) (title, body string) {
	if len(cp.Commits) == 1 {
		title = cp.Commits[0].FullSubject()
	} else {
		types := summarizeCommitTypes(cp.Commits)
		title = fmt.Sprintf("%d changes: %s", len(cp.Commits), types)
	}

	var sb strings.Builder
	if ticket != nil {
		fmt.Fprintf(&sb, "Ticket: %s\n\n", ticket.ID)
	}
	sb.WriteString("## Changes\n\n")
	for i, c := range cp.Commits {
		fmt.Fprintf(&sb, "%d. **%s**: %s\n", i+1, c.FullSubject(), commitFileList(c))
		if c.Body != nil && *c.Body != "" {
			fmt.Fprintf(&sb, "   %s\n", *c.Body)
		}
	}
	fmt.Fprintf(&sb, "\n---\n*Generated by intentra %s*\n", cp.ToolVersion)
	body = sb.String()
	return
}

func summarizeCommitTypes(commits []models.CommitUnit) string {
	seen := make(map[string]bool)
	var types []string
	for _, c := range commits {
		label := c.Type
		if c.Scope != nil && *c.Scope != "" {
			label += "(" + *c.Scope + ")"
		}
		if !seen[label] {
			seen[label] = true
			types = append(types, label)
		}
	}
	if len(types) > 5 {
		return strings.Join(types[:5], ", ") + fmt.Sprintf(" +%d more", len(types)-5)
	}
	return strings.Join(types, ", ")
}

func commitFileList(c models.CommitUnit) string {
	if len(c.Hunks) == 0 {
		return ""
	}
	return fmt.Sprintf("(%d hunk(s))", len(c.Hunks))
}

const maxPRLogCommits = 100

func buildPRFromGitLog(base string, ticket *artifacts.TicketRef) (title, body string) {
	rangeSpec := base + "..HEAD"
	ctx, cancel := localCtx()
	defer cancel()
	out, err := exec.CommandContext(ctx, "git", "log", "--oneline", "--no-decorate", rangeSpec).Output()
	if err != nil || len(strings.TrimSpace(string(out))) == 0 {
		return "Pull request", "Created with intentra."
	}

	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	totalCount := len(lines)

	if len(lines) == 1 {
		parts := strings.SplitN(lines[0], " ", 2)
		if len(parts) == 2 {
			title = parts[1]
		} else {
			title = lines[0]
		}
	} else {
		title = fmt.Sprintf("%d commits", totalCount)
	}

	if len(lines) > maxPRLogCommits {
		lines = lines[:maxPRLogCommits]
	}

	var sb strings.Builder
	if ticket != nil {
		fmt.Fprintf(&sb, "Ticket: %s\n\n", ticket.ID)
	}
	sb.WriteString("## Commits\n\n")
	for _, line := range lines {
		fmt.Fprintf(&sb, "- %s\n", line)
	}
	if totalCount > maxPRLogCommits {
		fmt.Fprintf(&sb, "\n*...and %d more commits*\n", totalCount-maxPRLogCommits)
	}
	body = sb.String()
	return
}
